Reducer
arti-zachara/19.1-Redux-Comments pull request #2
Opened 2019-06-10 08:13 UTC by arti-zachara

Task 19.4

2019-06-10 09:56 UTC, lukaszewczak requested changes

2019-06-10 09:56 UTC, lukaszewczak commented on comments.js
> +  switch (action.type) {
Ten reducer jest dedykowany dla komentarzy i state zawiera już tablicę komentarzy, dlatego wszystkie poniższe odwołania `state.comments` są błędne, ponieważ `state` jest tablicą a nie obiektem

2019-06-10 19:33 UTC, arti-zachara commented
zrobione

2019-06-11 20:39 UTC, lukaszewczak approved these changes

2019-06-11 20:39 UTC, merged